---
  - name: Install nginx
    apt: name={{ item }} update_cache=true state=latest
    loop: ['nginx']

  - name: Disable default site
    file:
            path: /etc/nginx/site-enabled/default
            state: absent
