---
  - name: Creating DB
    mysql_db:
            name: "{{ db_name }}"
            state: "present"
            login_user: "root"
            login_password: "{{ mysql_root_password }}"

  - name: Creating DB User
    mysql_user:
            name: "{{ db_user }}"
            password: "{{ db_password }}"
            priv: "{{ db_name }}.*:ALL"
            state: "present"
            login_user: "root"
            login_password: "{{ mysql_root_password }}"

  - name: Download WordPress
    get_url:
             url: "{{ download_url }}"
             dest: "/tmp/latest.tar.gz"
 
  - name: Creating Directory  WordPress
    file:
             path: "{{ wpdirectory }}"
             state: "directory"
             owner: "www-data"
             group: "www-data"

  - name: Unpack WordPress installation 
    ansible.builtin.unarchive:
             src: http://wordpress.org/latest.tar.gz
             dest: "{{ wpdirectory }}"
             remote_src: yes 
